sudo: required

services:
    - docker

before_install:
    - docker build -t manova1977/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true manova1977/docker-react npm run test


    