sudo: required

services:
    - docker

before_install:
    - docker build -t manova1977/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true manova1977/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-234324953568"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    
    